### ISSUE TITLE
`ValueError: Shape of variable ... ` when loading XL model

### ISSUE THREAD

**Issue by danyaljj** [google-research/multilingual-t5#10] opened 2020-10-28 06:39 UTC
I am using the same code for loading the models and getting the following error on the XL models, only: 

```
ValueError: Shape of variable decoder/block_000/layer_000/SelfAttention/k:0 ((1024, 1024)) doesn't match with shape of tensor decoder/block_000/layer_000/SelfAttention/k ([2048, 2048]) from checkpoint reader.
  In call to configurable 'run' (<function run at 0x7fe352ea0680>)
```

My code is pretty straightforward: 
(a) I have my tasks defined in my python code `parsiglue_tasks.py` 
(b) and in the commandline: 

```bash 
  python -m t5.models.mesh_transformer_main \
    --module_import="parsiglue_tasks" \
    --tpu="${TPU_NAME}" \
    --gcp_project="${PROJECT}" \
    --tpu_zone="${ZONE}" \
    --model_dir="${MODEL_DIR}" \
    --gin_file="dataset.gin" \
    --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
    --gin_param="utils.run.save_checkpoints_steps=1000" \
    --gin_param="utils.tpu_mesh_shape.tpu_topology = 'v3-8'" \
    --gin_param="MIXTURE_NAME = '${TASK}'" \
    --gin_param="utils.run.batch_size=('tokens_per_batch', 24576)" \
    --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS + FINETUNE_STEPS))" \
    --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
    --t5_tfds_data_dir="${BUCKET}/t5-tfds" \
    --gin_location_prefix="multilingual_t5/gin/"
```

My TPU software version is 2.2 and my virtual machine is hosting the following libraries: 
```
t5                       0.7.0
tensorboard              2.2.2
tensorboard-plugin-wit   1.7.0
tensorflow               2.2.1
tensorflow-datasets      4.0.1
tensorflow-estimator     2.2.0
tensorflow-metadata      0.24.0
tensorflow-text          2.2.0
```

**Comment by adarob** [comment] 2020-10-28 14:07
Thanks for reporting. There was an error in the operative configs. Should be fixed now.

**Closed by adarob** 2020-10-28 14:07 UTC

**Comment by acul3** [comment] 2020-10-28 15:37
i also got similar error just now

i'm trying to reproduce example notebook code in t5 repo,t5-trivia
(https://github.com/google-research/text-to-text-transfer-transformer/tree/master/notebooks)
by using mt5-xl instead of t5-xl

error code:
```
ValueError: Shape of variable decoder/logits/kernel:0 ((2048, 32128)) doesn't match with shape of tensor decoder/logits/kernel ([2048, 250112]) from checkpoint reader.
```

**Comment by adarob** [comment] 2020-10-28 15:49
That is a different error due to the vocabulary being different. You'll need to use the vocab at gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model
